/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ReportarRouteImport } from './routes/reportar'
import { Route as CasoCasoIdRouteImport } from './routes/caso.$casoId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportarRoute = ReportarRouteImport.update({
  id: '/reportar',
  path: '/reportar',
  getParentRoute: () => rootRouteImport,
} as any)
const CasoCasoIdRoute = CasoCasoIdRouteImport.update({
  id: '/caso/$casoId',
  path: '/caso/$casoId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/reportar': typeof ReportarRoute
  '/caso/$casoId': typeof CasoCasoIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/reportar': typeof ReportarRoute
  '/caso/$casoId': typeof CasoCasoIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/reportar': typeof ReportarRoute
  '/caso/$casoId': typeof CasoCasoIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/reportar' | '/caso/$casoId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/reportar' | '/caso/$casoId'
  id: '__root__' | '/' | '/reportar' | '/caso/$casoId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ReportarRoute: typeof ReportarRoute
  CasoCasoIdRoute: typeof CasoCasoIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reportar': {
      id: '/reportar'
      path: '/reportar'
      fullPath: '/reportar'
      preLoaderRoute: typeof ReportarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/caso/$casoId': {
      id: '/caso/$casoId'
      path: '/caso/$casoId'
      fullPath: '/caso/$casoId'
      preLoaderRoute: typeof CasoCasoIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ReportarRoute: ReportarRoute,
  CasoCasoIdRoute: CasoCasoIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
