/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AlertasRouteImport } from './routes/alertas'
import { Route as AnaliticaRouteImport } from './routes/analitica'
import { Route as AntesDespuesRouteImport } from './routes/antes-despues'
import { Route as BackRouteImport } from './routes/back'
import { Route as CentroRouteImport } from './routes/centro'
import { Route as CoberturasRouteImport } from './routes/coberturas'
import { Route as FlotaRouteImport } from './routes/flota'
import { Route as FrontRouteImport } from './routes/front'
import { Route as InformesRouteImport } from './routes/informes'
import { Route as ReportarRouteImport } from './routes/reportar'
import { Route as SeguimientoRouteImport } from './routes/seguimiento'
import { Route as SupervisionRouteImport } from './routes/supervision'
import { Route as CasoCasoIdRouteImport } from './routes/caso.$casoId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AlertasRoute = AlertasRouteImport.update({
  id: '/alertas',
  path: '/alertas',
  getParentRoute: () => rootRouteImport,
} as any)
const AnaliticaRoute = AnaliticaRouteImport.update({
  id: '/analitica',
  path: '/analitica',
  getParentRoute: () => rootRouteImport,
} as any)
const AntesDespuesRoute = AntesDespuesRouteImport.update({
  id: '/antes-despues',
  path: '/antes-despues',
  getParentRoute: () => rootRouteImport,
} as any)
const BackRoute = BackRouteImport.update({
  id: '/back',
  path: '/back',
  getParentRoute: () => rootRouteImport,
} as any)
const CentroRoute = CentroRouteImport.update({
  id: '/centro',
  path: '/centro',
  getParentRoute: () => rootRouteImport,
} as any)
const CoberturasRoute = CoberturasRouteImport.update({
  id: '/coberturas',
  path: '/coberturas',
  getParentRoute: () => rootRouteImport,
} as any)
const FlotaRoute = FlotaRouteImport.update({
  id: '/flota',
  path: '/flota',
  getParentRoute: () => rootRouteImport,
} as any)
const FrontRoute = FrontRouteImport.update({
  id: '/front',
  path: '/front',
  getParentRoute: () => rootRouteImport,
} as any)
const InformesRoute = InformesRouteImport.update({
  id: '/informes',
  path: '/informes',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportarRoute = ReportarRouteImport.update({
  id: '/reportar',
  path: '/reportar',
  getParentRoute: () => rootRouteImport,
} as any)
const SeguimientoRoute = SeguimientoRouteImport.update({
  id: '/seguimiento',
  path: '/seguimiento',
  getParentRoute: () => rootRouteImport,
} as any)
const SupervisionRoute = SupervisionRouteImport.update({
  id: '/supervision',
  path: '/supervision',
  getParentRoute: () => rootRouteImport,
} as any)
const CasoCasoIdRoute = CasoCasoIdRouteImport.update({
  id: '/caso/$casoId',
  path: '/caso/$casoId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/alertas': typeof AlertasRoute
  '/analitica': typeof AnaliticaRoute
  '/antes-despues': typeof AntesDespuesRoute
  '/back': typeof BackRoute
  '/centro': typeof CentroRoute
  '/coberturas': typeof CoberturasRoute
  '/flota': typeof FlotaRoute
  '/front': typeof FrontRoute
  '/informes': typeof InformesRoute
  '/reportar': typeof ReportarRoute
  '/seguimiento': typeof SeguimientoRoute
  '/supervision': typeof SupervisionRoute
  '/caso/$casoId': typeof CasoCasoIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/alertas': typeof AlertasRoute
  '/analitica': typeof AnaliticaRoute
  '/antes-despues': typeof AntesDespuesRoute
  '/back': typeof BackRoute
  '/centro': typeof CentroRoute
  '/coberturas': typeof CoberturasRoute
  '/flota': typeof FlotaRoute
  '/front': typeof FrontRoute
  '/informes': typeof InformesRoute
  '/reportar': typeof ReportarRoute
  '/seguimiento': typeof SeguimientoRoute
  '/supervision': typeof SupervisionRoute
  '/caso/$casoId': typeof CasoCasoIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/alertas': typeof AlertasRoute
  '/analitica': typeof AnaliticaRoute
  '/antes-despues': typeof AntesDespuesRoute
  '/back': typeof BackRoute
  '/centro': typeof CentroRoute
  '/coberturas': typeof CoberturasRoute
  '/flota': typeof FlotaRoute
  '/front': typeof FrontRoute
  '/informes': typeof InformesRoute
  '/reportar': typeof ReportarRoute
  '/seguimiento': typeof SeguimientoRoute
  '/supervision': typeof SupervisionRoute
  '/caso/$casoId': typeof CasoCasoIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/alertas'
    | '/analitica'
    | '/antes-despues'
    | '/back'
    | '/centro'
    | '/coberturas'
    | '/flota'
    | '/front'
    | '/informes'
    | '/reportar'
    | '/seguimiento'
    | '/supervision'
    | '/caso/$casoId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/alertas'
    | '/analitica'
    | '/antes-despues'
    | '/back'
    | '/centro'
    | '/coberturas'
    | '/flota'
    | '/front'
    | '/informes'
    | '/reportar'
    | '/seguimiento'
    | '/supervision'
    | '/caso/$casoId'
  id:
    | '__root__'
    | '/'
    | '/alertas'
    | '/analitica'
    | '/antes-despues'
    | '/back'
    | '/centro'
    | '/coberturas'
    | '/flota'
    | '/front'
    | '/informes'
    | '/reportar'
    | '/seguimiento'
    | '/supervision'
    | '/caso/$casoId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AlertasRoute: typeof AlertasRoute
  AnaliticaRoute: typeof AnaliticaRoute
  AntesDespuesRoute: typeof AntesDespuesRoute
  BackRoute: typeof BackRoute
  CentroRoute: typeof CentroRoute
  CoberturasRoute: typeof CoberturasRoute
  FlotaRoute: typeof FlotaRoute
  FrontRoute: typeof FrontRoute
  InformesRoute: typeof InformesRoute
  ReportarRoute: typeof ReportarRoute
  SeguimientoRoute: typeof SeguimientoRoute
  SupervisionRoute: typeof SupervisionRoute
  CasoCasoIdRoute: typeof CasoCasoIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/alertas': {
      id: '/alertas'
      path: '/alertas'
      fullPath: '/alertas'
      preLoaderRoute: typeof AlertasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analitica': {
      id: '/analitica'
      path: '/analitica'
      fullPath: '/analitica'
      preLoaderRoute: typeof AnaliticaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/antes-despues': {
      id: '/antes-despues'
      path: '/antes-despues'
      fullPath: '/antes-despues'
      preLoaderRoute: typeof AntesDespuesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/back': {
      id: '/back'
      path: '/back'
      fullPath: '/back'
      preLoaderRoute: typeof BackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/centro': {
      id: '/centro'
      path: '/centro'
      fullPath: '/centro'
      preLoaderRoute: typeof CentroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/coberturas': {
      id: '/coberturas'
      path: '/coberturas'
      fullPath: '/coberturas'
      preLoaderRoute: typeof CoberturasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/flota': {
      id: '/flota'
      path: '/flota'
      fullPath: '/flota'
      preLoaderRoute: typeof FlotaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/front': {
      id: '/front'
      path: '/front'
      fullPath: '/front'
      preLoaderRoute: typeof FrontRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/informes': {
      id: '/informes'
      path: '/informes'
      fullPath: '/informes'
      preLoaderRoute: typeof InformesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reportar': {
      id: '/reportar'
      path: '/reportar'
      fullPath: '/reportar'
      preLoaderRoute: typeof ReportarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/seguimiento': {
      id: '/seguimiento'
      path: '/seguimiento'
      fullPath: '/seguimiento'
      preLoaderRoute: typeof SeguimientoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/supervision': {
      id: '/supervision'
      path: '/supervision'
      fullPath: '/supervision'
      preLoaderRoute: typeof SupervisionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/caso/$casoId': {
      id: '/caso/$casoId'
      path: '/caso/$casoId'
      fullPath: '/caso/$casoId'
      preLoaderRoute: typeof CasoCasoIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AlertasRoute: AlertasRoute,
  AnaliticaRoute: AnaliticaRoute,
  AntesDespuesRoute: AntesDespuesRoute,
  BackRoute: BackRoute,
  CentroRoute: CentroRoute,
  CoberturasRoute: CoberturasRoute,
  FlotaRoute: FlotaRoute,
  FrontRoute: FrontRoute,
  InformesRoute: InformesRoute,
  ReportarRoute: ReportarRoute,
  SeguimientoRoute: SeguimientoRoute,
  SupervisionRoute: SupervisionRoute,
  CasoCasoIdRoute: CasoCasoIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
