CREATE TABLE public.catalogo_etapas (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nombre public.etapa_caso NOT NULL UNIQUE,
  orden smallint NOT NULL UNIQUE,
  es_cierre boolean NOT NULL DEFAULT false,
  en_atencion boolean NOT NULL DEFAULT false
);

CREATE TABLE public.catalogo_servicios (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nombre text NOT NULL UNIQUE,
  prometido_min integer NOT NULL CHECK (prometido_min > 0)
);

CREATE TABLE public.catalogo_ciudades (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nombre text NOT NULL UNIQUE,
  mapa_x numeric NOT NULL CHECK (mapa_x BETWEEN 0 AND 100),
  mapa_y numeric NOT NULL CHECK (mapa_y BETWEEN 0 AND 100)
);

INSERT INTO public.catalogo_etapas (nombre, orden, es_cierre, en_atencion) VALUES
('Creación', 1, false, false),
('Trámite', 2, false, false),
('Asignado', 3, false, false),
('Llegada a sitio', 4, false, true),
('En atención', 5, false, true),
('Traslado', 6, false, true),
('Finalizado', 7, true, false),
('Cierre', 8, true, false)
ON CONFLICT (nombre) DO UPDATE SET
  orden = EXCLUDED.orden,
  es_cierre = EXCLUDED.es_cierre,
  en_atencion = EXCLUDED.en_atencion;

INSERT INTO public.catalogo_servicios (nombre, prometido_min) VALUES
('Grúa de gran tonelaje', 60),
('Rescate', 45),
('Asistencia jurídica', 45),
('Carro taller', 45),
('Movilidad del conductor', 45)
ON CONFLICT (nombre) DO UPDATE SET prometido_min = EXCLUDED.prometido_min;

INSERT INTO public.catalogo_ciudades (nombre, mapa_x, mapa_y) VALUES
('Bogotá', 39, 34),
('Medellín', 33, 26),
('Barranquilla', 41, 12),
('Cali', 30, 58),
('Neiva', 36, 66)
ON CONFLICT (nombre) DO UPDATE SET
  mapa_x = EXCLUDED.mapa_x,
  mapa_y = EXCLUDED.mapa_y;

GRANT SELECT ON public.catalogo_etapas TO anon, authenticated;
GRANT SELECT ON public.catalogo_servicios TO anon, authenticated;
GRANT SELECT ON public.catalogo_ciudades TO anon, authenticated;

GRANT ALL ON public.catalogo_etapas TO service_role;
GRANT ALL ON public.catalogo_servicios TO service_role;
GRANT ALL ON public.catalogo_ciudades TO service_role;

ALTER TABLE public.catalogo_etapas ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.catalogo_servicios ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.catalogo_ciudades ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Demo: ver etapas" ON public.catalogo_etapas
FOR SELECT TO anon, authenticated USING (true);

CREATE POLICY "Demo: ver servicios" ON public.catalogo_servicios
FOR SELECT TO anon, authenticated USING (true);

CREATE POLICY "Demo: ver ciudades" ON public.catalogo_ciudades
FOR SELECT TO anon, authenticated USING (true);
