CREATE TYPE public.etapa_caso AS ENUM (
  'Creación','Trámite','Asignado','Llegada a sitio','En atención','Traslado','Finalizado','Cierre'
);

CREATE TABLE public.casos (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  numero integer GENERATED BY DEFAULT AS IDENTITY (START WITH 1040) UNIQUE,
  placa text NOT NULL,
  tipo_servicio text NOT NULL,
  ciudad text NOT NULL,
  ubicacion text NOT NULL DEFAULT '',
  tipo_vehiculo text NOT NULL DEFAULT 'Pesado',
  etapa public.etapa_caso NOT NULL DEFAULT 'Creación',
  prometido_min integer NOT NULL DEFAULT 45,
  creado_en timestamptz NOT NULL DEFAULT now(),
  actualizado_en timestamptz NOT NULL DEFAULT now(),
  mapa_x numeric NOT NULL DEFAULT 40,
  mapa_y numeric NOT NULL DEFAULT 40,
  origen text NOT NULL DEFAULT 'Agente IA'
);

CREATE TABLE public.eventos_caso (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  caso_id uuid NOT NULL REFERENCES public.casos(id) ON DELETE CASCADE,
  etapa public.etapa_caso NOT NULL,
  ocurrido_en timestamptz NOT NULL DEFAULT now(),
  nota text
);

CREATE INDEX eventos_caso_caso_id_idx ON public.eventos_caso(caso_id);

GRANT SELECT, INSERT, UPDATE ON public.casos TO anon, authenticated;
GRANT SELECT, INSERT ON public.eventos_caso TO anon, authenticated;
GRANT ALL ON public.casos TO service_role;
GRANT ALL ON public.eventos_caso TO service_role;

ALTER TABLE public.casos ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.eventos_caso ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Demo: ver casos" ON public.casos FOR SELECT TO anon, authenticated USING (true);
CREATE POLICY "Demo: crear casos" ON public.casos FOR INSERT TO anon, authenticated WITH CHECK (true);
CREATE POLICY "Demo: actualizar casos" ON public.casos FOR UPDATE TO anon, authenticated USING (true) WITH CHECK (true);
CREATE POLICY "Demo: ver eventos" ON public.eventos_caso FOR SELECT TO anon, authenticated USING (true);
CREATE POLICY "Demo: crear eventos" ON public.eventos_caso FOR INSERT TO anon, authenticated WITH CHECK (true);

INSERT INTO public.casos (placa, tipo_servicio, ciudad, ubicacion, tipo_vehiculo, etapa, prometido_min, creado_en, mapa_x, mapa_y) VALUES
('WTX-234','Grúa de gran tonelaje','Bogotá','Vía Bogotá-Girardot, peaje Chusacá','Pesado','Llegada a sitio',45, now() - interval '28 minutes', 38, 34),
('KJR-901','Rescate','Medellín','Túnel de Occidente, km 3','Pesado','En atención',50, now() - interval '41 minutes', 34, 26),
('PLM-558','Asistencia jurídica','Barranquilla','Circunvalar con Cra 38','Liviano','Traslado',60, now() - interval '88 minutes', 41, 12),
('ZVC-117','Carro taller','Cali','Autopista Sur con Cra 50','Pesado','Asignado',40, now() - interval '12 minutes', 30, 58),
('HQN-402','Movilidad del conductor','Neiva','Vía Neiva-Campoalegre km 8','Liviano','Trámite',45, now() - interval '35 minutes', 36, 66),
('BTR-776','Grúa de gran tonelaje','Bogotá','Calle 80 con Cra 100','Pesado','Creación',45, now() - interval '6 minutes', 40, 36),
('GFT-209','Grúa de gran tonelaje','Bogotá','Autopista Norte km 21','Pesado','Asignado',60, now() - interval '75 minutes', 41, 32),
('DRC-330','Rescate','Medellín','Las Palmas, km 12','Pesado','En atención',45, now() - interval '40 minutes', 33, 28),
('VBN-615','Carro taller','Cali','Vía Cali-Jamundí','Pesado','Llegada a sitio',45, now() - interval '67 minutes', 31, 60),
('MZN-341','Movilidad del conductor','Barranquilla','Vía 40 con Calle 72','Liviano','Finalizado',45, now() - interval '110 minutes', 42, 14),
('RDF-405','Asistencia jurídica','Neiva','Av. Circunvalar con Calle 19','Liviano','Cierre',60, now() - interval '180 minutes', 35, 68),
('TNP-673','Rescate','Bogotá','Vía Bogotá-La Calera km 6','Liviano','Traslado',50, now() - interval '54 minutes', 39, 33);

WITH etapas AS (
  SELECT e.etapa, e.ord FROM unnest(enum_range(NULL::public.etapa_caso)) WITH ORDINALITY AS e(etapa, ord)
)
INSERT INTO public.eventos_caso (caso_id, etapa, ocurrido_en)
SELECT c.id,
       et.etapa,
       c.creado_en + ((et.ord - 1)::numeric * (EXTRACT(epoch FROM (now() - c.creado_en)) / GREATEST(cur.ord - 1, 1)) * interval '1 second')
FROM public.casos c
JOIN etapas cur ON cur.etapa = c.etapa
JOIN etapas et ON et.ord <= cur.ord;